### ISSUE TITLE
Reference to local package Tailwindcss

### ISSUE THREAD

**Issue by jamesddube** [adamwathan/laracon2017#7]
`"tailwindcss": "file:../tailwindcss"`

Included in the package.json is the tailwind library which I believe is still in development (as of this time) and not yet available in the npm repo. Therefore I cant install this dependency through yarn or npm install.
Or maybe there's a workaround i'm missing?

**Comment by adamwathan** [comment]
Pushed some changes to work around that 👍

**Comment by jamesddube** [comment]
Thanks!
